stages:
  download_datasets:
    cmd: uv run python -m src.dataset
    params:
    - config/data/amzn.yaml:
      - dataset_name
    - config/data/sent140.yaml:
      - dataset_name
    outs:
    - data/raw

  preprocess:
    cmd: uv run python -m src.preprocessor
    deps:
    - data/raw/Reviews.csv
    - data/raw/training.1600000.processed.noemoticon.csv
    - src/preprocessor.py
    outs:
    - data/processed/reviews.parquet

  build_index:
    cmd: uv run python -m src.pipelines.build_index model=bm25
    deps:
    - data/processed/reviews.parquet
    outs:
    - models/bm25_index.pkl
    params:
    - config/models/bm25.yaml:
      - k1
      - b
    metrics:
    - reports/metrics.json

  evaluate:
    cmd: uv run python -m src.pipelines.evaluate
    deps:
    - models/bm25_index.pkl


