defaults:
#make multiple datasets in the config/data directory
- data: [amzn, sent140]
- model: bm25
paths:
model_path: model/
reports_path: reports
preprocessor_path: model/preprocessor.pkl

experiment_name: my_experiment